global:
  storageClass: longhorn
auth:
  existingSecret: redis-password-secret
  existingSecretPasswordKey: password

image:
  tag: 7.2.4-debian-12-r12

architecture: replication

master:
  count: 1
  persistence:
    size: 200Gi
  service:
    type: NodePort
    nodePorts:
      redis: 31459
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - cache
  tolerations:
    - effect: NoSchedule
      key: role
      value: cache
    - effect: NoSchedule
      key: dept
      value: dc

  resources:
    # requests:
    #   cpu: 8
    #   memory: 512Mi
    limits:
      cpu: 4
      memory: 48Gi

replica:
  replicaCount: 2
  persistence:
    size: 200Gi
  service:
    type: NodePort
    nodePorts:
      redis: 30234
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  tolerations:
    - effect: NoSchedule
      key: dept
      value: dc
    - effect: NoSchedule
      key: role
      value: cache
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - cache
  resources:
    limits:
      cpu: 4
      memory: 48Gi
  

sentinel:
  enabled: false

# volumePermissions:
#   enabled: true
