# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-conf
  namespace: redis-stack
data:
  redis.conf: | 
    bind 0.0.0.0
    protected-mode no
    save 60 10

