apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc  # Name of the new PVC
  namespace: mongodb  # Replace with your namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # The size of the PVC
  storageClassName: longhorn  # Your desired storage class (replace if needed)