architecture: replicaset
replicaSet:
  enabled: true
  replicas: 3

arbiter:
  enabled: false

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: latest
  pullPolicy: IfNotPresent

auth:
  enabled: true
  rootPassword: 7TgZq2aHvW8xP4l
  username: admin
  password: Q8xgmPZ2rV5w
  database: admin

service:
  type: NodePort
  port: 27017
  nodePort: 31743

persistence:
  enabled: true
  existingClaim: mongodb-pvc  # Use the existing PersistentVolumeClaim

resources:
  requests:
    memory: "4Gi"
    cpu: "1"
  limits:
    memory: "8Gi"
    cpu: "2"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - av4-4-127
