---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-stack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack-deployment
  namespace: redis-stack
  labels:
    app: redis-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      nodeSelector:
        
      containers:
        - name: redis-stack
          image: redis/redis-stack-server:latest
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: redis-stack-data
      restartPolicy: Always
      volumes:
        - name: redis-stack-data
          persistentVolumeClaim:
            claimName: redis-stack-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack-service
  namespace: redis-stack
  labels:
    app: redis-stack
spec:
  type: NodePort
  selector:
    app: redis-stack
  ports:
    - port: 6379
      nodePort: 30379
---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: redis-stack
  name: redis-stack-pvc
  labels:
    app: redis-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs-sc
---
