# Opaque Secret — contains sensitive values. Prefer not committing this file to public repos;
# use Sealed Secrets, External Secrets, or private-only branches.
apiVersion: v1
kind: Secret
metadata:
  name: koneksi-backend-secret
type: Opaque
stringData:
  APP_KEY: "7Qx8R2nU6pL3mF9sT1wZ4gH0jK5cE8bA"
  JWT_SECRET: "A9KvN2mQ5tR8wL3jF6hB4cD1gE0iH7pM2nO9rS6tU4xW1yZ3aE5bF8gH2jL9mP6qS4tV7wX0zA3dF6gH9jM2pO5rT8uW1yZ4bE7hK0nQ3sV6xA9cF2iL5oR8tU1wZ4gH7j"
  REDIS_PASSWORD: "uR8tV4wZ7gH2jM5pS1xA9cF6iL0oQ3nE"
  MONGO_PASSWORD: "05yY6kamQqsqUMPg"
  MONGO_CONNECTION_STRING: "mongodb://staging:05yY6kamQqsqUMPg@125.6.40.238:27017/?authSource=koneksi&replicaSet=rs0"
  POSTGRES_PASSWORD: "1hZj4KtL5k4gZ3Kg"
  SPACES_KEY: "DO00H2MCMN3WF2F9RUFF"
  SPACES_SECRET: "ng0T5G5SkOaNE2jN0W/DpQs9RokvtFgO+ZGm959+4h4"
  IPFS_AUTHORIZATION: "Bearer uqvT3vJkqtLqyRZB6sXvHdteukQtqkkN"
  POSTMARK_API_KEY: "26d847a1-3798-47ea-a9e8-5b5abf9bc37b"
  PORTONE_SECRET_KEY: "8IDteYgidREIhijMReyi3T1K1xpGnRDg5SuXudqugjETcKlpZWImyd284oFKPt1U0rMPeJanczzAyLjk"
  PORTONE_WEBHOOK_SECRET: "whsec_wYz+LZc6rTKtPo6vja6XuA8auDyGP0aVOHVTZhIaFuA="
  PORTONE_INICIS_MONTHLY_CHANNEL_KEY: "channel-key-cdaab6b9-cbd3-487c-b41d-e290b5d5617a"
  PORTONE_INICIS_YEARLY_CHANNEL_KEY: "channel-key-29b0f9ce-cff0-4221-92e0-3dd487d3ea84"
  PORTONE_PAYPAL_CHANNEL_KEY: "channel-key-e64c7cb8-8712-4f72-b912-17ff7b8c24a8"
  PROVENANCE_SERVICE_TOKEN: "d22ee182496ca6f5ed0475143e61c434e1e746e6aa672c39a8557951a73623bc"
  VAULT_ROLE_ID: "bdfc98d2-bc21-b195-ee51-63931dcd43b6"
  VAULT_SECRET_ID: "1f7f8632-0a15-0c2b-4a44-fbb421336eba"
