# global:
#   storageClass: gp3
# image:
#   tag: 5.0.15-debian-11-r14
architecture: replicaset
arbiter:
  enabled: false
replicaCount: 3
auth:
  existingSecret: mongo-eks-secret
  usernames:
    - devs
  databases:
    - init_db
# initdbScripts:
#   setup_replicaset_script.js: |
#     rs.initiate();
#     rs.add("mongodb-0.mongodb-headless:27017");
#     rs.add("mongodb-1.mongodb-headless:27017");
#     rs.add("mongodb-2.mongodb-headless:27017");
tolerations:
  - operator: Exists
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cache
              operator: In
              values:
                - "true"
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - mongodb
        topologyKey: kubernetes.io/hostname

persistence:
  storageClass: local-path
  size: 2Gi
persistentVolumeClaimRetentionPolicy:
  enabled: true
automountServiceAccountToken: true
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    type: NodePort
    nodePorts:
      - 30000
      - 30001
      - 30002
    # port: 27017
    # loadBalancerIPs:
    #   - 184.169.197.183
    #   - 13.57.125.195
    #   - 52.52.123.136
rbac:
  create: true
serviceAccount:
  create: true
initContainers:
  - command:
      - sh
      - -c
      - sysctl -w vm.max_map_count=262144
    image: busybox
    name: sysctl
    securityContext:
      privileged: true
      runAsUser: 0

readinessProbe:
  enabled: true

resourcesPreset: large
# resources:
#   limits:
#     cpu: 3
#     memory: 12Gi
