apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  annotations:
    meta.helm.sh/release-name: image-updater
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/instance: image-updater
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/version: v0.12.2
    helm.sh/chart: argocd-image-updater-0.9.1
data:
  registries.conf: |
    registries:
      - name: NHN NCR (koneksi-tech)
        prefix: 36163004-kr1-registry.container.nhncloud.com/koneksi-tech
        api_url: https://36163004-kr1-registry.container.nhncloud.com
        credentials: pullsecret:argocd/ncr-regcred
        default: true
        ping: true
  argocd.grpc_web: "true"
  argocd.insecure: "false"
  argocd.plaintext: "false"
  kube.events: "false"
  log.level: info
