apiVersion: v1
kind: Secret
metadata:
  name: repo-bitbucket-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@bitbucket.org:metawhale/manifests-seven-gen.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAvmnSjeJztSFqoFK1+uS2JWVn1Vj9WBOhdO9hC1QLZ6UKNp9rW1uN
    VMoDXYoej62fe/q2vLCqKB0nLZFNbFNSJLbaGKm1Z9s1yJtV3tNwBnevuoYa7LiJEoiyLQ
    +r4T0aHetDQGDPQEVAqDclGo7LjEuHh0Bo5owSHaUb+2WNaagRF5C1t+Rmn1Nf+l59oHvc
    BeMZVUogn6QEo1WDxOuqhYvAw83yrGDl5teq6M8rHBD2oCa1PqKFwo8yc8mf93ggIQYn4e
    XQoe7DXKKP4hDiiunufIyQmKKJ1huEdytrPr4jPR/uR/46gevRFriyQoOxFu+fac2gRsLW
    26qqwJPmeQAAA9iwjY/YsI2P2AAAAAdzc2gtcnNhAAABAQC+adKN4nO1IWqgUrX65LYlZW
    fVWP1YE6F072ELVAtnpQo2n2tbW41UygNdih6PrZ97+ra8sKooHSctkU1sU1IkttoYqbVn
    2zXIm1Xe03AGd6+6hhrsuIkSiLItD6vhPRod60NAYM9ARUCoNyUajsuMS4eHQGjmjBIdpR
    v7ZY1pqBEXkLW35GafU1/6Xn2ge9wF4xlVSiCfpASjVYPE66qFi8DDzfKsYOXm16rozysc
    EPagJrU+ooXCjzJzyZ/3eCAhBifh5dCh7sNcoo/iEOKK6e58jJCYoonWG4R3K2s+viM9H+
    5H/jqB69EWuLJCg7EW759pzaBGwtbbqqrAk+Z5AAAAAwEAAQAAAQEAo1H4+yHExROIdUL8
    O9p4MNMtoFzXz/fmgHnh7umDbr6sZ/WNC6sXKiarhEu3stzk8l405ttQ119J/1el5MgCqO
    L9ZjIKGq53Dz3NBXatm56E56Om7GvLhk4hJW1Pq73Q7OChqlJe8W1069OAy6q3A/q0oFmq
    oDR8RVkdCyArjvbQBK2TwHoqM4WRqoZEfriY2Oh6wzy1FG9lDCDyh21GoHNmFkN8l7WNwM
    83P/kQK0K6JCwms5eVRTtkdNytA00YXdhYQmKE7hMjZC8vsidlxAcYAClW+rNDbqYXke/S
    gHrajjkzv3EAccPTK0kYnFR5G8H1W4P/PbsZ3c01pA9SAQAAAIEAgy3G6096TmyEa3NKEx
    oV3pMD6NE4IcsKEEJY/pBJbCIesB1bKXBiqBVrSp3CsFR8mMpaicTPcGLa61+6ETQnl+zQ
    sRIlBJCWm5cpE1AiArtvM3P4sEG6Pjv4u0xWdu3ny6EUk9ZU9E8L5HJAuyK6woeaei1k+7
    dz8yIZmfbeof0AAACBAPUGvwuYiX0kwWWhj9tJGzgi8pvAJTlXVeenlwbPrDzJkInL25qW
    jNUXLmZUjjwvrwz4J6KVBl/yuhFA8N3m92JUHwqQi8QIUkd3crvIRQTIw9SujWwemv2+EH
    EIQaVjdYcWx6TSeLSsbkBfbEE6XJeyHCLU6eL1RM2Z1Uorw7VpAAAAgQDG8O6zOLRAxAoY
    ANtj7R09e7eejmNeA5bh4/GlmQ2+AfX5lrd5BlpDBiShpvX4gP/vyDYcX4xnjWlHYTitzr
    sXVy7TBHbjs2M9gYeK76pGYTtXZh5esn2++5mX+mt5YZuXdpKSUrli6wV+k4Bgwf6+Fyd1
    9lMoqWn2kArPPgY2kQAAAB9jZWRyaWNrLnRhYmFyZXNAbWVkaWEtbWV0ZXIuY29tAQI=
    -----END OPENSSH PRIVATE KEY-----
