apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-client-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi  # Adjust based on your needs