mode: distributed
replicas: 3
persistence:
  enabled: true
  storageClass: "nfs-storage-class-nas3" # requires nfs-storage-class-nas3
  accessMode: ReadWriteOnce
  size: 100Gi
resources:
  limits:
    memory: "2Gi"
    cpu: "1000m"
environment:
  MINIO_BROWSER: "on"
service:
  type: ClusterIP

# command: helm install minio minio/minio -f minIO/NAS3/values.yml --namespace minio-operator

# NAME: minio
# LAST DEPLOYED: Tue Nov  5 10:49:13 2024
# NAMESPACE: minio-operator
# STATUS: deployed
# REVISION: 1
# TEST SUITE: None
# NOTES:
# MinIO can be accessed via port 9000 on the following DNS name from within your cluster:
# minio.minio-operator.cluster.local

# To access MinIO from localhost, run the below commands:
#   1. export POD_NAME=$(kubectl get pods --namespace minio-operator -l "release=minio" -o jsonpath="{.items[0].metadata.name}")
#   2. kubectl port-forward $POD_NAME 9000 --namespace minio-operator

# Read more about port forwarding here: http://kubernetes.io/docs/user-guide/kubectl/kubectl_port-forward/

# You can now access MinIO server on http://localhost:9000. Follow the below steps to connect to MinIO server with mc client:
#   1. Download the MinIO mc client - https://min.io/docs/minio/linux/reference/minio-mc.html#quickstart
#   2. export MC_HOST_minio-local=http://$(kubectl get secret --namespace minio-operator minio -o jsonpath="{.data.rootUser}" | base64 --decode):$(kubectl get secret --namespace minio-operator minio -o jsonpath="{.data.rootPassword}" | base64 --decode)@localhost:9000
#   3. mc ls minio-local